name: Release

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "npm"
                  scope: "@bgalek"
                  registry-url: "https://registry.npmjs.org"

            - name: Get latest tag and update version
              run: npm version $(git tag | sort -r --version-sort | head -n1 | cut -c2-) -no-git-tag-version -f

            - name: Install dependencies
              run: npm ci

            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
